name: Run Python Script After Another Workflow

on:
  workflow_run:
    workflows: ["Run Python Scripts and Commit CSV Files"]
    types:
      - completed

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Check for CSV Files
        run: |
          if [ -n "$(find . -maxdepth 1 -name '*.csv' -print -quit)" ]; then
            echo "CSV files found. Deleting..."
            find . -type f -name "*.csv" -delete
          else
            echo "No CSV files found. Skipping deletion."
            exit 0  # Exit successfully to skip the next steps
          fi

      - name: Commit and Push Changes
        if: success()  # Only run this step if the previous step was successful
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Delete CSV files"
          git push

      - name: Run Python Script
        run: |
          python DebtHoldings.py

      - name: Commit CSV files
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add *.csv  # Replace 'path/to/your/csv/files' with the actual path
          git commit -m "Auto-commit CSV files" || true  # Continue even if there are no changes
          git push
