name: Run Python Script After Another Workflow

on:
  workflow_run:
    workflows: ["Run Python Scripts and Commit CSV Files"]
    types:
      - completed

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Python Script
        run: |
          python DebtHoldings.py
