name: Run Python Script

on:
  workflow_dispatch:  # Triggered manually
  schedule:
    - cron: '0 0,12 * * *'  # Run every 12 hours

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Ensure correct Python version is installed

      - name: Check for CSV Files
        run: |
          if [ -n "$(find . -maxdepth 1 -name '*.csv' -print -quit)" ]; then
            echo "CSV files found. Deleting..."
            find . -type f -name "*.csv" -delete
          else
            echo "No CSV files found. Skipping deletion."
            exit 0  # Exit successfully to skip the next steps

      - name: Install dependencies in virtual environment
        if: success()  # Only run this step if the previous step was successful
        run: |
          python -m venv venv  # Create virtual environment
          source venv/bin/activate  # Activate virtual environment
          python -m pip install --upgrade pip  # Upgrade pip within venv
          pip install requests pandas  # Install dependencies

      - name: Run Python Script
        if: success()  # Only run this step if the previous step was successful
        run: |
          source venv/bin/activate  # Activate virtual environment
          python MFCode.py
          python StkCode.py
          python DebtHoldings.py
          python Data_clean.py

      - name: Commit CSV files
        if: success()  # Only run this step if the previous step was successful
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add *.csv  # Add CSV files
          git commit -m "Auto-commit CSV files" || true  # Continue even if there are no changes
          git push
