name: Run Python Script

on:
  workflow_dispatch:  # Triggered manually
  schedule:
    - cron: '0 0,12 * * *'  # Run every 12 hours

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository B
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Check for CSV Files
        run: |
          if [ -n "$(find . -maxdepth 1 -name '*.csv' -print -quit)" ]; then
            echo "CSV files found. Deleting..."
            find . -type f -name "*.csv" -delete
          else
            echo "No CSV files found. Skipping deletion."
            exit 0  # Exit successfully to skip the next steps
          fi
      - name: Commit and Push Changes
        if: success()  # Only run this step if the previous step was successful
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Delete CSV files"
          git push

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests pandas

      - name: Run Python Script
        run: |
          python DebtHoldings.py
          python Data_clean.py

      - name: Commit CSV files
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add *.csv  # Replace 'path/to/your/csv/files' with the actual path
          git commit -m "Auto-commit CSV files" || true  # Continue even if there are no changes
          git push
